### ISSUE TITLE
[PE-D][Tester E] GUI not scaling to the right size

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F12-3/tp#119]
![image.png](https://raw.githubusercontent.com/tanshiyu1999/ped/main/files/7a3798d7-e796-41b6-980d-525937307cb6.png)

Your GUI does not scale properly when the size becomes too large. There is a huge whitebox below it.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: tanshiyu1999/ped#1

**Comment by teozern1** [comment]
GUI now extends to the full window
