### ISSUE TITLE
[PE-D][Tester B] Telegram handle should have stricter checks.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F12-3/tp#146]
How to reproduce:
`add n/ADVERSARY p/18003555353 e/xy@x.com s/ tele/!`
`add n/ADVERSARY p/18003555353 e/xy@x.com s/ tele/_____`

Expected Behaviour: All the above should not be allowed. Telegram handles can only be of certain lengths and have certain characters. Furthermore, we must have them start with a `@`, much like in your sample persons provided, such as `@berNICE`.

Current Behaviour: No checks are given, except for if it is empty.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: et-irl/ped#8

**Comment by teozern1** [comment]
feature enhancement
