### ISSUE TITLE
[PE-D][Tester B] Tooltip for `addModule` is inaccurate.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F12-3/tp#161]
`Module codes should only contain alphanumeric characters and it should be 5-6 characters`

How to reproduce:
`addModule m/ASFCIASFKJKCSAOCSAPCX02`

Expected behaviour:
The above should not be valid input.

Current behaviour:
It is allowed.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: et-irl/ped#13

**Comment by supermii2** [comment]
Duplicate of #145

**Comment by jacksonyuan256** [comment]
Closed - see Pull Request #218  Fix bugs for delete module
