### ISSUE TITLE
[PE-D][Tester A] TUTORIAL_TIME field in addToTutorial does not work for just 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F12-3/tp#167]
By typing `addTutorial m/CS1000 tn/T12 tt/ 6PM`, there's no further output on the command box, even though 6PM is a valid TUTORIAL_TIME. Error is shown in terminal. 

There is no indication of what's the format of input for TUTORIAL_TIME. 

![Screenshot 2023-11-03 at 4.48.40 PM.png](https://raw.githubusercontent.com/GlendaChong/ped/main/files/9692258e-c940-4d65-b272-c850aa260b61.png)

![Screenshot 2023-11-03 at 4.51.43 PM.png](https://raw.githubusercontent.com/GlendaChong/ped/main/files/e7ae4a81-bfa5-48de-a7ea-253f0af912f3.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: GlendaChong/ped#9

**Comment by Propene-Dan** [comment]
added details about format of TUTORIAL_TIME in UG
