### ISSUE TITLE
[PE-D][Tester C] Search command duplicate prefixes does not work

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F12-3/tp#197]
Before:
![image.png](https://raw.githubusercontent.com/jingjie88/ped/main/files/9042c591-c8cc-4d33-bea7-fd05417b42de.png)

After:
![image.png](https://raw.githubusercontent.com/jingjie88/ped/main/files/226a99ef-f19a-4a3e-9ac2-5d938f84483f.png)

Search commands with duplicate prefixes for name seem to always fail since the search commands appears to only display users that match all prefixes.

Perhaps one way to fix this would be to not allow duplicate prefixes for name. Another possible fix is to have the search feature return users that match any of the criteria similar to AB3's find feature (i.e. the example shown in the image above should return Bernice Yu and David Li). 

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: jingjie88/ped#13

**Comment by supermii2** [comment]
Intended behavior. Agree that it should be limited to one name per search if this is the case.
