### ISSUE TITLE
[PE-D][Tester C] Minor UI bug: app title is still same as AB3

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F12-3/tp#199]
![image.png](https://raw.githubusercontent.com/jingjie88/ped/main/files/35f01a5a-efd2-4586-9494-0135f7353f8f.png)

Don't forget to change the app title to TASsistant before the actual PE. This can be done in MainWindow.fxml.

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: jingjie88/ped#14

**Comment by teozern1** [comment]
Changed to TAssistant
