### ISSUE TITLE
Tests for addToTutorial & RemoveFromTutorial

### ISSUE THREAD

**Issue by cbj252** [AY2324S1-CS2103T-F12-3/tp#86]
Leftover work from v1.2:

- Parser needs to take in only the name of the tutorial rather than both the name and the time.
- Tests for AddToTutorial, AddToTutorialParser, RemoveFromTutorial, RemoveFromTutorialParser & parts of Tutorial edited
- Get rid of the additional stuff from v1.2 (tutorials being in a separate folder from the other commands, the extra exceptions in the Tutorial class)

**Comment by Propene-Dan** [comment]
taking the parser

**Comment by Propene-Dan** [comment]
done, but need testing to find bugs and edge cases.

**Comment by Propene-Dan** [comment]
fixed bugs
